/**
 * Golden-corpus test: `test/times/fixtures/times-golden.v2.json` (schemaVersion 2,
 * calculatorVersion 3, 284 cases), generated by the real iOS app's
 * `EntryTimesCalculator`/`DetailedTimes`/`EASATimes` with the night v2 algorithm
 * (shared verbatim with the Jetlog backend and iOS app). Every case
 * must match exactly on every field.
 *
 * Each case carries a `catalog` and `userPlaces`. The harness builds the index with
 * the REAL resolver (`buildAirportIndex`) and resolves the entry's derived from/to
 * through the REAL `resolve`, so a mismatch is attributed to resolution (`resolved`)
 * or to the night math separately. `derivedDate` and `inPeriod` pin the derived-date
 * rule and the shared period predicate.
 * See `docs/TIMES.md`.
 */
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { buildAirportIndex, resolve, type CatalogRow, type ResolvedAirport, type UserPlace } from "../../src/airports/index.js";
import { calculateEntryTimes, derivedDate, derivedRoute } from "../../src/times/calculator.js";
import { CALCULATOR_VERSION, inPeriod, type Period } from "../../src/times/index.js";
import type { Airport, AircraftTypeInfo, CalcContext, CalcEntry, CalcPerson, EntryPersonRoleName } from "../../src/times/types.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FIXTURE_PATH = path.join(__dirname, "fixtures", "times-golden.v2.json");

interface ExpectedResolved {
  identity: string;
  hasPosition: boolean;
  lat: number | null;
  lon: number | null;
  timezone: string | null;
}

interface GoldenCase {
  name: string;
  category: string;
  input: {
    activeCrewCount: number;
    catalog: CatalogRow[];
    userPlaces: UserPlace[];
    period: Period | null;
    aircraft?: { easaCertification: string; engineCount: number; icaoType: string; registration: string };
    entry: Record<string, unknown>;
    manualTimes?: Record<string, unknown>;
    selfRole: string;
  };
  expected: {
    detailedTimes?: Record<string, unknown>;
    easaTimesSigned?: Record<string, unknown>;
    easaTimesUnsigned?: Record<string, unknown>;
    night?: number;
    resolved: { from: ExpectedResolved | null; to: ExpectedResolved | null };
    derivedDate: string;
    inPeriod: boolean | null;
  };
}

interface GoldenFixture {
  schemaVersion: number;
  calculatorVersion: number;
  cases: GoldenCase[];
}

const fixture: GoldenFixture = JSON.parse(readFileSync(FIXTURE_PATH, "utf-8"));
const cases = fixture.cases;

/** Deletes keys whose value is `undefined` so a stripped actual-output
 * object can be compared directly against the fixture's `expected` object
 * (which never serializes absent keys). */
function stripUndefined<T extends Record<string, unknown>>(obj: T): T {
  const copy = { ...obj };
  for (const key of Object.keys(copy)) {
    if (copy[key] === undefined) delete copy[key];
  }
  return copy;
}

/** The golden corpus encodes the iOS app's unknown-role case
 * as the literal string `"unknown(XYZ)"`. Collapse any such string to the
 * calculator's `"unknown"` role name. `undefined` (the `missing_no_self_person`
 * case has no `selfRole` key at all) passes through, mirroring "no person on
 * this entry matches self", see `CalcContext.selfRole`'s doc comment. */
function normalizeRole(raw: string | undefined): EntryPersonRoleName | undefined {
  if (raw === undefined) return undefined;
  if (raw.startsWith("unknown(")) return "unknown";
  return raw as EntryPersonRoleName;
}

function buildCalcEntry(rawEntry: Record<string, unknown>): CalcEntry {
  const rawPeople = (rawEntry.people as { personId: string; role: string; isDeleted?: boolean }[]) ?? [];
  const people: CalcPerson[] = rawPeople.map((p) => ({
    personId: p.personId,
    role: normalizeRole(p.role),
    isDeleted: p.isDeleted
  }));

  return {
    date: rawEntry.date as string,
    type: rawEntry.type as string,
    from: rawEntry.from as string | undefined,
    to: rawEntry.to as string | undefined,
    offBlocks: rawEntry.offBlocks as string | undefined,
    onBlocks: rawEntry.onBlocks as string | undefined,
    airborne: rawEntry.airborne as string | undefined,
    touchdown: rawEntry.touchdown as string | undefined,
    registration: rawEntry.registration as string | undefined,
    registrationSystem: rawEntry.registrationSystem as string | undefined,
    offBlocksSystem: rawEntry.offBlocksSystem as string | undefined,
    onBlocksSystem: rawEntry.onBlocksSystem as string | undefined,
    airborneSystem: rawEntry.airborneSystem as string | undefined,
    touchdownSystem: rawEntry.touchdownSystem as string | undefined,
    systemDate: rawEntry.systemDate as string | undefined,
    systemFrom: rawEntry.systemFrom as string | undefined,
    systemTo: rawEntry.systemTo as string | undefined,
    actualFrom: rawEntry.actualFrom as string | undefined,
    actualTo: rawEntry.actualTo as string | undefined,
    updateFlightData: (rawEntry.updateFlightData as boolean) ?? false,
    ifr: (rawEntry.ifr as boolean) ?? true,
    isImportedFromOtherLogbook: (rawEntry.isImportedFromOtherLogbook as boolean) ?? false,
    isBulk: (rawEntry.isBulk as boolean) ?? false,
    aircraftIcaoCode: rawEntry.aircraftIcaoCode as string | undefined,
    startTime: rawEntry.startTime as string | undefined,
    endTime: rawEntry.endTime as string | undefined,
    people
    // manualTimes is attached by the caller (already correctly minute-shaped).
  };
}

/**
 * Stays empty: a night mismatch now means this port deviates from the night
 * v2 spec (there is no platform-specific float32 behaviour left to excuse it).
 */
export const KNOWN_NIGHT_MISMATCHES: { name: string; expected: number | undefined; got: number | undefined; analysis: string }[] = [];

function toCalcAirport(airport: ResolvedAirport | null): Airport | undefined {
  if (!airport) return undefined;
  return airport.hasPosition ? { hasPosition: true, lat: airport.lat!, lon: airport.lon! } : { hasPosition: false, lat: null, lon: null };
}

function expectResolved(actual: ResolvedAirport | null, expected: ExpectedResolved | null): void {
  if (expected === null) {
    expect(actual).toBeNull();
    return;
  }
  expect(actual).not.toBeNull();
  expect({
    identity: actual!.identity,
    hasPosition: actual!.hasPosition,
    lat: actual!.lat,
    lon: actual!.lon,
    timezone: actual!.timezone
  }).toEqual(expected);
}

describe("times golden corpus (times-golden.v2.json)", () => {
  it("pins the corpus schema and calculator version", () => {
    expect(fixture.schemaVersion).toBe(2);
    expect(fixture.calculatorVersion).toBe(CALCULATOR_VERSION);
  });

  it("has 284 cases (fixture sanity check)", () => {
    expect(cases.length).toBe(284);
  });

  for (const testCase of cases) {
    it(`${testCase.category} / ${testCase.name}`, () => {
      const calcEntry = buildCalcEntry(testCase.input.entry);
      if (testCase.input.manualTimes) {
        calcEntry.manualTimes = testCase.input.manualTimes as CalcEntry["manualTimes"];
      }

      const index = buildAirportIndex(testCase.input.catalog, testCase.input.userPlaces);
      const lookupAirport = (code: string): Airport | undefined => toCalcAirport(resolve(index, code));
      const ctx: CalcContext = {
        selfRole: normalizeRole(testCase.input.selfRole),
        activeCrewCount: testCase.input.activeCrewCount,
        lookupAirport,
        // Empirically, every non-bulk
        // `aircraft_classification` case's `expected.detailedTimes` has no
        // singlePilotSingleEngine/singlePilotMultiEngine/multiPilot field at
        // all, even though `input.aircraft` is present and
        // `input.entry.registration` is set (the generator's registration
        // normalization never matched a real row). But
        // `bulk_with_aircraft_classification` does expect classification to
        // resolve, via `entry.aircraftIcaoCode` matching
        // `input.aircraft.icaoType` directly. Keying this lookup on an exact
        // match against `icaoType` reproduces both. See docs/TIMES.md.
        lookupAircraftType: (key: string): AircraftTypeInfo | undefined => {
          const aircraft = testCase.input.aircraft;
          if (!aircraft || key !== aircraft.icaoType) return undefined;
          return {
            easaCertification: aircraft.easaCertification as AircraftTypeInfo["easaCertification"],
            engineCount: aircraft.engineCount
          };
        }
      };

      const result = calculateEntryTimes(calcEntry, ctx);

      const knownMismatch = KNOWN_NIGHT_MISMATCHES.find((m) => m.name === testCase.name);
      if (knownMismatch) {
        expect(result.night).toBe(knownMismatch.got);
      } else {
        expect(result.night).toBe(testCase.expected.night);
      }

      expect(stripUndefined(result.detailedTimes)).toEqual(testCase.expected.detailedTimes ?? {});
      expect(stripUndefined(result.easaTimesSigned)).toEqual(testCase.expected.easaTimesSigned ?? {});
      expect(stripUndefined(result.easaTimesUnsigned)).toEqual(testCase.expected.easaTimesUnsigned ?? {});

      // Resolution and the derived-date rule, asserted separately from the night math.
      const route = derivedRoute(calcEntry);
      expectResolved(resolve(index, route.from), testCase.expected.resolved.from);
      expectResolved(resolve(index, route.to), testCase.expected.resolved.to);
      expect(derivedDate(calcEntry)).toBe(testCase.expected.derivedDate);
      const period = testCase.input.period;
      expect(period === null ? null : inPeriod(derivedDate(calcEntry), period)).toBe(testCase.expected.inPeriod);
    });
  }
});
